"""Go Cold's dims write surface (M-DIMS phase).

The first CC write surface, ported natively into the W0–W5 spine (M-DIMS-1 Route B).
M-DIMS-2 is shadow mode: read current dims, compute the diff, require approval, run
the full gate chain — but inject a recorder so nothing is written. Shadow vs live
(M-DIMS-3) differ by a single injected mutate fn (WRITE_ENABLEMENT_PLAN §3.1).
"""
from .approve import (
    approve_dims_write,
    shadow_mutate_fn,
    read_product_for_dims,
    DimsApproveResult,
    ProductDimsRead,
    DIM_FIELDS,
    PRODUCT_PATH,
)
from .roundtrip import (
    live_mutate_fn,
    write_and_verify,
    assert_write_target_allowed,
    gather_active_sandbox_candidates,
    select_writable_sandbox_sku,
    run_sandbox_roundtrip,
    sandbox_desired_lookup,
    SandboxCandidate,
    TargetSelection,
    HardStopInfo,
    RoundtripReport,
    DimsRoundtripError,
    DimsRoundtripRefused,
    NoWritableSandboxSku,
    DimsReadBackMismatch,
)
from .bulk import (
    build_bulk_plan,
    run_sandbox_bulk,
    run_ct_bulk,
    run_each_bulk,
    resolve_ct_uom,
    resolve_default_uom,
    format_ct_bulk_report,
    format_each_bulk_report,
    BulkPlan,
    BulkPlanItem,
    BulkReport,
)
from .capture import (
    mm_to_cm,
    captured_cc_dims_table,
    MM_PER_CM,
)
from .uom_name import (
    uom_name_status,
    UomNameStatus,
    UOM_NAME_MIN_CHARS,
    UOM_NAME_MAX_CHARS,
)
from .ct_probe import (
    classify_ct_uom,
    ct_uom_name,
    probe_ct_uom_names,
    format_ct_uom_census,
    CtUomProbe,
    CtUomCensus,
    CT_NAME_MIN_CHARS,
    CT_NAME_MAX_CHARS,
)
from .each_probe import (
    classify_each_uom,
    resolve_base_uom,
    probe_each_uom_names,
    format_each_uom_census,
    EachUomProbe,
    EachUomCensus,
)
from .live_proving import (
    gather_active_live_candidates,
    select_live_proving_targets,
    build_live_proving_plan,
    run_live_proving,
    disarm_reminder,
    finalize_exit,
    LiveCandidate,
    LiveTarget,
    LiveProvingPlan,
    LiveHardStopInfo,
    LiveProvingReport,
    LiveProvingRefused,
)

__all__ = [
    "approve_dims_write",
    "shadow_mutate_fn",
    "read_product_for_dims",
    "DimsApproveResult",
    "ProductDimsRead",
    "DIM_FIELDS",
    "PRODUCT_PATH",
    "live_mutate_fn",
    "write_and_verify",
    "assert_write_target_allowed",
    "gather_active_sandbox_candidates",
    "select_writable_sandbox_sku",
    "run_sandbox_roundtrip",
    "sandbox_desired_lookup",
    "SandboxCandidate",
    "TargetSelection",
    "HardStopInfo",
    "RoundtripReport",
    "DimsRoundtripError",
    "DimsRoundtripRefused",
    "NoWritableSandboxSku",
    "DimsReadBackMismatch",
    "build_bulk_plan",
    "run_sandbox_bulk",
    "run_ct_bulk",
    "run_each_bulk",
    "resolve_ct_uom",
    "resolve_default_uom",
    "format_ct_bulk_report",
    "format_each_bulk_report",
    "BulkPlan",
    "BulkPlanItem",
    "BulkReport",
    "mm_to_cm",
    "captured_cc_dims_table",
    "MM_PER_CM",
    "uom_name_status",
    "UomNameStatus",
    "UOM_NAME_MIN_CHARS",
    "UOM_NAME_MAX_CHARS",
    "classify_ct_uom",
    "ct_uom_name",
    "probe_ct_uom_names",
    "format_ct_uom_census",
    "CtUomProbe",
    "CtUomCensus",
    "CT_NAME_MIN_CHARS",
    "CT_NAME_MAX_CHARS",
    "classify_each_uom",
    "resolve_base_uom",
    "probe_each_uom_names",
    "format_each_uom_census",
    "EachUomProbe",
    "EachUomCensus",
    "gather_active_live_candidates",
    "select_live_proving_targets",
    "build_live_proving_plan",
    "run_live_proving",
    "disarm_reminder",
    "finalize_exit",
    "LiveCandidate",
    "LiveTarget",
    "LiveProvingPlan",
    "LiveHardStopInfo",
    "LiveProvingReport",
    "LiveProvingRefused",
]
